#!/bin/bash
#Purpose: CKA s2 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman117/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace=""
object=""
object_name="ns/svc-field | deploy/front-end"
object_replicas=""
yaml_path=https://raw.githubusercontent.com/Bookman117/CKA_Tutorial/main/yaml/
yaml="f10_preprocess"

#Main program
set-text-color-variable
echo -e "${YELLOW}f10 preprocess:${NC}"

#建立指定物件
kubectl create -f ${yaml_path}${yaml}.yaml > /dev/null 2>&1 && echo -e " [${GREEN}●${NC}] ${object_name} created." || echo -e " [${RED}●${NC}] ${object_name} already exist."