#!/bin/bash
#Purpose: CKA s2 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace=""
object=""
object_name="ns/label-field | pod/cpu-stress-test-*"
object_replicas=""
yaml_path=https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/yaml/
yaml="f6_preprocess"

#Main program
set-text-color-variable
echo -e "${YELLOW}f14 preprocess:${NC}"

#CRD deploy
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

#CLone project
git clone https://github.com/kubernetes-csi/csi-driver-host-path.git

#部署腳本
./csi-driver-host-path/deploy/kubernetes-1.24-test/deploy.sh
