#!/bin/bash
#Purpose: CKA s2 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace=""
object=""
object_name="ns/ing-internal | pod/hi | svc/hi"
object_replicas=""
yaml_path=https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/yaml/
yaml="f3_preprocess"

#Main program
set-text-color-variable
echo -e "${YELLOW}f3 preprocess:${NC}"

#建立指定物件
kubectl create -f ${yaml_path}${yaml}.yaml > /dev/null 2>&1 && echo -e " [${GREEN}●${NC}] ${object_name} created." || echo -e " [${RED}●${NC}] ${object_name} already exist."

#複寫 nginx 網站內容
kubectl get pod hi -n ing-internal --no-headers | grep "1/1   Running" &> /dev/null
while true
    do
        kubectl get pod hi -n ing-internal --no-headers | grep "1/1   Running" &> /dev/null
        [ "${?}" == "0" ] && break
    done
[ "${?}" == "0" ] && kubectl exec -it hi -n ing-internal -- sh -c "echo "hi" > index.html" 2> /dev/null && echo -e " [${GREEN}●${NC}] nginx index.html configured." || echo -e " [${RED}●${NC}] nginx index.html not configured."