#!/bin/bash
#Purpose: CKA s2 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace=""
object=""
object_name=""
object_replicas=""
yaml_path=https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/yaml/
yaml=""

#Main program
set-text-color-variable
echo -e "${YELLOW}f8 preprocess:${NC}"

#將 kubelet 路徑指向改為錯誤路徑
ssh 92-w1 "sudo sed -i 's/\/usr\/bin\/kubelet/\/var\/bin\/kubelet/g' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
ssh 92-w1 "sudo systemctl daemon-reload"
ssh 92-w1 "sudo systemctl restart kubelet"
ssh 92-w1 'sudo systemctl status kubelet' | grep 'activating (auto-restart)' &> /dev/null && echo -e " [${GREEN}●${NC}] 92-w1 kubelet destroyed." || echo -e " [${RED}●${NC}] ${object_name} 92-w1 kubelet running well."