#!/bin/bash
#Purpose: CKA s7 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace=""
object=""
object_name=""
object_replicas=""
yaml_path=~/
yaml=""

#Main program
set-text-color-variable
echo -e "${YELLOW}s7 preprocess:${NC}"
create_topic_dir /opt/course/7