#!/bin/bash
#Purpose: CKA all environment preprocess
#Create-Date: 2023-07-06

#Variable
source ~/bin/preprocess_function

#Main program
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/s1_cleanups' | bash