#!/bin/bash
#Purpose: CKA s3 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/preprocess_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/preprocess_function' -O ~/bin/preprocess_function
source ~/bin/preprocess_function
target_namespace="project-hamster"
object=""
object_name=""
object_replicas=0
yaml_path=https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/
yaml=""

#Main program
set-text-color-variable
echo -e "${YELLOW}s3 preprocess:${NC}"
#檢查並建立 namespace
namespace_detector=0
kubectl get ns ${target_namespace} > /dev/null 2>&1 || namespace_detector=1
[ "${namespace_detector}" == "0" ] && echo -e " [${GREEN}●${NC}] ${target_namespace} already exist."
[ "${namespace_detector}" == "1" ] && kubectl create ns ${target_namespace} > /dev/null 2>&1 && echo -e " [${GREEN}●${NC}] ${target_namespace} created."