#!/bin/bash
#Purpose: CKA s6 environment preprocess
#Create-Date: 2023-07-06

#Variable
source https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/function
set-text-color-variable
target_namespace="project-tiger"
object=""
object_name=""
object_replicas=""
yaml_path=~/
yaml=""

#Main program
#檢查並建立 namespace
namespace_detector=0
kubectl get ns ${target_namespace} > /dev/null 2>&1 || namespace_detector=1
[ "${namespace_detector}" == "0" ] && echo -e " [${GREEN}●${NC}] ${target_namespace} already exist."
[ "${namespace_detector}" == "1" ] && kubectl create ns ${target_namespace} > /dev/null 2>&1 && echo -e " [${GREEN}●${NC}] ${target_namespace} created."