#!/bin/bash
#Purpose: CKA s1 environment preprocess
#Create-Date: 2023-07-06

#Variable
source https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/function
set-text-color-variable
target_namespace=""
object=""
object_name=""
object_replicas=""
yaml_path=~/
yaml=""

#Main program
create_topic_dir /opt/course/7