#!/bin/bash
#Purpose: CKA s1 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/preprocess_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/preprocess_function' -O ~/bin/preprocess_function
source ~/bin/preprocess_function
set-text-color-variable
target_namespace=""
object=""
object_name=""
object_replicas=""
yaml_path=~/
yaml=""

#Main program
create_topic_dir /opt/course/7