#!/bin/bash
#Purpose: CKA s3 environment cleanup
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace="project-c13"
object="sts"
object_name="o3db"
object_replicas=2
yaml_path=https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/yaml/
yaml="s3_preprocess"

#Main program
set-text-color-variable
echo -e "${YELLOW}s4 cleanup:${NC}"

#檢查並刪除 object
object_detector=0
kubectl get ${object} -n ${target_namespace} 2>&1 | grep "${object_name}" > /dev/null && object_detector=1
[ "${object_detector}" == "0" ] && echo -e " [${GREEN}●${NC}] ${object_name} already exist."
[ "${object_detector}" == "1" ] && kubectl delete -f ${yaml_path}${yaml}.yaml > /dev/null 2>&1 && echo -e " [${GREEN}●${NC}] ${object}/${object_name} deleted."

#檢查並刪除 namespace
namespace_detector=0
kubectl get ns ${target_namespace} > /dev/null 2>&1 && namespace_detector=1
[ "${namespace_detector}" == "0" ] && echo -e " [${GREEN}●${NC}] ${target_namespace} not exist."
[ "${namespace_detector}" == "1" ] && kubectl delete ns ${target_namespace} > /dev/null 2>&1 && echo -e " [${GREEN}●${NC}] ${target_namespace} deleted."