#!/bin/bash
#Purpose: CKA s6 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman117/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace="project-tiger"
object=""
object_name=""
object_replicas=""
yaml_path=~/
yaml=""

#Main program
set-text-color-variable
echo -e "${YELLOW}s6 cleanups:${NC}"
#刪除物件
kubectl delete deploy safari -n ${target_namespace} &> /dev/null
kubectl delete pvc safari-pvc -n ${target_namespace} &> /dev/null
kubectl delete pv safari-pv -n ${target_namespace} &> /dev/null
#檢查並建立 namespace
namespace_detector=0
kubectl get ns ${target_namespace} > /dev/null 2>&1 && namespace_detector=1
[ "${namespace_detector}" == "0" ] && echo -e " [${GREEN}●${NC}] ${target_namespace} not exist."
[ "${namespace_detector}" == "1" ] && kubectl delete ns ${target_namespace} > /dev/null 2>&1 && echo -e " [${GREEN}●${NC}] ${target_namespace} deleted."