#!/bin/bash
#Purpose: CKA s8 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace="default"
object="pod"
object_name="manual-schedule manual-schedule2"
object_replicas=""
yaml_path=~/
yaml=""

#Main program
set-text-color-variable
for list in ${object_name}
    do
        #檢查並刪除 object
        object_detector=0
        kubectl get ${object} -n ${target_namespace} 2>&1 | grep "${list}" > /dev/null && object_detector=1
        [ "${object_detector}" == "0" ] && echo -e " [${GREEN}●${NC}] ${list} not exist."
        [ "${object_detector}" == "1" ] && kubectl delete ${object} ${list} -n ${target_namespace} > /dev/null 2>&1 && echo -e " [${GREEN}●${NC}] ${object}/${list} deleted."
    done