#!/bin/bash
#Purpose: CKA all environment preprocess
#Create-Date: 2023-07-06

#Variable
wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/preprocess_function
source ~/bin/preprocess_function

#Main program
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s1_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s2_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s3_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s4_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s5_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s6_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s7_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s8_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s10_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s11_score' | bash
curl -s 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/score/s12_score' | bash