#!/bin/bash
#Purpose: CKA s1 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace=""
object=""
object_name=""
object_replicas=""
yaml_path=~/
yaml=""

#Main program
set-text-color-variable
echo -e "${YELLOW}s1 score:${NC}"
context_list=$(kubectl config get-contexts -o name)
target_number=$(cat /opt/course/1/contexts | wc -l)
current_number=$(kubectl config get-contexts -o name | wc -l)

[ "${target_number}" == "${current_number}" ] && for list in ${context_list}
    do
        echo -e " [${GREEN}●${NC}] ${list} correct."
    done && echo -e " [${GREEN}●${NC}] s1 scored." || echo -e " [${RED}●${NC}] ${list} s1 not scored."