#!/bin/bash
#Purpose: CKA s1 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace="default"
object="pod"
object_name="pod1"
object_replicas=""
yaml_path=~/
yaml=""

#Main program
target_container_name=pod1-container
set-text-color-variable
echo -e "${YELLOW}s2 score:${NC}"

#Check sts replicas
kubectl get sts -n project-c13 | grep 'o3db' | awk '{ print $2 }' | grep '/1' &> /dev/null && echo -e " [${GREEN}●${NC}] sts replicas correct." || echo -e " [${RED}●${NC}] sts replicas incorrect."