#!/bin/bash
#Purpose: CKA s1 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace="default"
object="pod"
object_name="pod1"
object_replicas=""
yaml_path=~/
yaml=""

#Main program
target_container_name=pod1-container
set-text-color-variable
echo -e "${YELLOW}s6 score:${NC}"

#kubectl get pods -A --sort-by=.metadata.creationTimestamp | tail -n +2 | head -n 1
#kubectl get pods -A --sort-by=.metadata.uid | tail -n +2 | head -n 1
#echo "kubectl get pods -A --sort-by=.metadata.creationTimestamp" > /opt/course/5/find_pods.sh
#echo "kubectl get pods -A --sort-by=.metadata.uid" > /opt/course/5/find_pods_uid.sh

cat /opt/course/5/find_pods.sh | grep 'kubectl get pods -A --sort-by=.metadata.creationTimestamp' &> /dev/null && echo -e " [${GREEN}●${NC}] find_pods.sh currect." || echo -e " [${RED}●${NC}] find_pods.sh incurrect."
cat /opt/course/5/find_pods_uid.sh | grep 'kubectl get pods -A --sort-by=.metadata.uid' &> /dev/null && echo -e " [${GREEN}●${NC}] find_pods_uid.sh currect." || echo -e " [${RED}●${NC}] find_pods_uid.sh incurrect. "