#!/bin/bash
#Purpose: CKA s1 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace="default"
object="pod"
object_name="pod1"
object_replicas=""
yaml_path=~/
yaml=""

#Main program
target_container_name=pod1-container
set-text-color-variable
echo -e "${YELLOW}s6 score:${NC}"

kubectl get pv -n project-tiger | grep '^safari-pv' | grep '2Gi' | grep 'RWO' | grep 'Bound' | grep 'project-tiger/safari-pvc' &> /dev/null && echo -e " [${GREEN}●${NC}] safari-pv currect." || echo -e " [${RED}●${NC}] safari-pv incurrect."
kubectl get pvc -n project-tiger | grep '^safari-pvc' | grep '2Gi' | grep 'RWO' | grep 'Bound' &> /dev/null && echo -e " [${GREEN}●${NC}] safari-pvc currect." || echo -e " [${RED}●${NC}] safari-pvc incurrect."

node_name=$(kubectl get po -n project-tiger -o wide | awk '{ print $7 }' | tail -n +2)
ssh ${node_name} 'ls /Volumes/Data' &> /dev/null && echo -e " [${GREEN}●${NC}] hostPath currect." || echo -e " [${RED}●${NC}] hostPath incurrect."