#!/bin/bash
#Purpose: CKA s1 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace="default"
object="pod"
object_name="pod1"
object_replicas=""
yaml_path=~/
yaml=""

#Main program
target_container_name=pod1-container
set-text-color-variable
echo -e "${YELLOW}s7 score:${NC}"

cat /opt/course/7/node.sh | grep 'kubectl top nodes' &> /dev/null && echo -e " [${GREEN}●${NC}] node.sh currect." || echo -e " [${RED}●${NC}] node.sh incurrect."
cat /opt/course/7/pod.sh | grep 'kubectl top pods --containers=true' &> /dev/null && echo -e " [${GREEN}●${NC}] pod.sh currect." || echo -e " [${RED}●${NC}] pod.sh incurrect."