#!/bin/bash
#Purpose: CKA s1 environment preprocess
#Create-Date: 2023-07-06

#Variable
ls ~/bin/cka_function &> /dev/null || wget -q 'https://raw.githubusercontent.com/Bookman-W/CKA_Tutorial/main/script/cka_function' -O ~/bin/cka_function
source ~/bin/cka_function
target_namespace="default"
object="pod"
object_name="pod1"
object_replicas=""
yaml_path=~/
yaml=""

#Main program
target_container_name=pod1-container
set-text-color-variable
echo -e "${YELLOW}s8 score:${NC}"

cat /opt/course/8/master-components.txt | grep 'kubelet' | awk '{ print $2 }' | grep 'process'  &> /dev/null && echo -e " [${GREEN}●${NC}] kubelet currect." || echo -e " [${RED}●${NC}] kubelet incurrect."
cat /opt/course/8/master-components.txt | grep 'kube-apiserver' | awk '{ print $2 }' | grep 'static-pod'  &> /dev/null && echo -e " [${GREEN}●${NC}] kube-apiserver currect." || echo -e " [${RED}●${NC}] kube-apiserver incurrect."
cat /opt/course/8/master-components.txt | grep 'kube-scheduler' | awk '{ print $2 }' | grep 'static-pod'  &> /dev/null && echo -e " [${GREEN}●${NC}] kube-scheduler currect." || echo -e " [${RED}●${NC}] kube-scheduler incurrect."
cat /opt/course/8/master-components.txt | grep 'kube-controller-manager' | awk '{ print $2 }' | grep 'static-pod'  &> /dev/null && echo -e " [${GREEN}●${NC}] kube-controller-manager currect." || echo -e " [${RED}●${NC}] kube-controller-manager incurrect."
cat /opt/course/8/master-components.txt | grep 'etcd' | awk '{ print $2 }' | grep 'static-pod'  &> /dev/null && echo -e " [${GREEN}●${NC}] etcd currect." || echo -e " [${RED}●${NC}] etcd incurrect."

cat /opt/course/8/master-components.txt | grep 'dns' | awk '{ print $2,$3 }' | grep 'pod coredns' &> /dev/null && echo -e " [${GREEN}●${NC}] dns currect." || echo -e " [${RED}●${NC}] dns incurrect."